package javaProgram;

// Generated by Selenium IDE






import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class T1Test<findElement> {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeClass
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
 
  @Test
  public void t1() {
    driver.get("https://opensource-demo.orangehrmlive.com/index.php/auth/login");
   
    driver.manage().window().setSize(new Dimension(1040, 754));
    driver.findElement(By.id("txtUsername")).click();
    driver.findElement(By.id("txtUsername")).sendKeys("admin");
    driver.findElement(By.id("frmLogin")).click();
    driver.findElement(By.id("frmLogin")).click();
    driver.findElement(By.id("txtPassword")).click();
    driver.findElement(By.id("txtPassword")).sendKeys("admin1");
    driver.findElement(By.id("btnLogin")).click();
    driver.findElement(By.id("task-list-group-panel-menu_holder")).click();
  } @AfterClass
  public void tearDown(){
	    driver.quit();
	  }
}

